sudo: false
dist: trusty

language: haxe

haxe:
  - development

addons:
  apt:
    packages:
    - mono-devel
    - mono-mcs

install:
  - haxelib install hxcs
  - haxelib install utest
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
  - haxelib install mcover
  - haxelib git mcover https://github.com/massiveinteractive/mcover master src

script:
  - haxe test-js.hxml
  - node bin/test.js
  - haxe test-cs.hxml
  - mono bin/test_cs/bin/TestMain.exe

