// Generated by Haxe 4.0.0 (git build development @ 8366563)
(function () { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var classy_core_RawValueConverter = function() { };
classy_core_RawValueConverter.__name__ = true;
var MyEnum = { __ename__ : true, __constructs__ : ["A","B","C","D"] };
MyEnum.A = ["A",0];
MyEnum.A.toString = $estr;
MyEnum.A.__enum__ = MyEnum;
MyEnum.B = function(v) { var $x = ["B",1,v]; $x.__enum__ = MyEnum; $x.toString = $estr; return $x; };
MyEnum.C = function(v) { var $x = ["C",2,v]; $x.__enum__ = MyEnum; $x.toString = $estr; return $x; };
MyEnum.D = function(e) { var $x = ["D",3,e]; $x.__enum__ = MyEnum; $x.toString = $estr; return $x; };
var MyEnum2 = { __ename__ : true, __constructs__ : ["A"] };
MyEnum2.A = function(v) { var $x = ["A",0,v]; $x.__enum__ = MyEnum2; $x.toString = $estr; return $x; };
var classy_core_ValueBase = function() { };
classy_core_ValueBase.__name__ = true;
classy_core_ValueBase.prototype = {
	__link: function(parent,name) {
		if(this.__parent != null) {
			throw new js__$Boot_HaxeError("Object is already linked");
		}
		this.__parent = parent;
		this.__name = name;
		this.__setup(this.__parent.__transaction,this.__parent.__dbChanges);
	}
	,__unlink: function() {
		this.__parent = null;
		this.__name = null;
		this.__dbChanges = null;
	}
	,__setup: function(transaction,dbChanges) {
		this.__transaction = transaction;
		this.__dbChanges = dbChanges;
	}
	,__makeFieldPath: function(path) {
		var object = this;
		while(object.__parent != null) {
			var name = object.__name;
			var end = name.length;
			var i = name.length;
			while(i-- > 0) if(name.charCodeAt(i) == 46) {
				path.push(name.substring(i + 1,end));
				end = i;
			}
			path.push(name.substring(0,end));
			object = object.__parent;
		}
		path.reverse();
		return path;
	}
};
var classy_core_Value = function() { };
classy_core_Value.__name__ = true;
classy_core_Value.__super__ = classy_core_ValueBase;
classy_core_Value.prototype = $extend(classy_core_ValueBase.prototype,{
});
var Player = function() {
	this.set_some("Hi");
};
Player.__name__ = true;
Player.__fromRawValue = function(raw) {
	var instance = Object.create(Player.prototype);
	instance.set_some(raw.some);
	return instance;
};
Player.__super__ = classy_core_Value;
Player.prototype = $extend(classy_core_Value.prototype,{
	set_some: function(value) {
		var _gthis = this;
		var oldValue = this.some;
		if(oldValue != value) {
			this.some = value;
			if(this.__transaction != null) {
				this.__transaction.rollbacks.push(function() {
					return _gthis.some = oldValue;
				});
			}
			if(this.__dbChanges != null) {
				var fieldPath = this.__makeFieldPath(["some"]);
				this.__dbChanges.changes.push(value != null ? { kind : "set", path : fieldPath, value : value} : { kind : "delete", path : fieldPath});
			}
		}
		return value;
	}
	,__toRawValue: function() {
		var raw = { };
		if(this.some != null) {
			raw.some = this.some;
		}
		return raw;
	}
});
var Some = function() {
	this.set_some("Hi");
};
Some.__name__ = true;
Some.__fromRawValue = function(raw) {
	var instance = Object.create(Some.prototype);
	instance.set_some(raw.some);
	return instance;
};
Some.__super__ = classy_core_Value;
Some.prototype = $extend(classy_core_Value.prototype,{
	set_some: function(value) {
		var _gthis = this;
		var oldValue = this.some;
		if(oldValue != value) {
			this.some = value;
			if(this.__transaction != null) {
				this.__transaction.rollbacks.push(function() {
					return _gthis.some = oldValue;
				});
			}
			if(this.__dbChanges != null) {
				var fieldPath = this.__makeFieldPath(["some"]);
				this.__dbChanges.changes.push(value != null ? { kind : "set", path : fieldPath, value : value} : { kind : "delete", path : fieldPath});
			}
		}
		return value;
	}
	,__toRawValue: function() {
		var raw = { };
		if(this.some != null) {
			raw.some = this.some;
		}
		return raw;
	}
});
var Data = function() {
};
Data.__name__ = true;
Data.__fromRawValue = function(raw) {
	var instance = Object.create(Data.prototype);
	instance.set_value(MyEnum_$_$RawValueConverter.instance.fromRawValue(raw.value));
	return instance;
};
Data.__super__ = classy_core_Value;
Data.prototype = $extend(classy_core_Value.prototype,{
	set_value: function(value) {
		var _gthis = this;
		var oldValue = this.value;
		if(oldValue != value) {
			if(oldValue != null) {
				MyEnum_$_$Helper.instance.unlink(oldValue);
			}
			if(value != null) {
				MyEnum_$_$Helper.instance.link(value,this,"value");
			}
			this.value = value;
			if(this.__transaction != null) {
				this.__transaction.rollbacks.push(function() {
					return _gthis.value = oldValue;
				});
			}
			if(this.__dbChanges != null) {
				var fieldPath = this.__makeFieldPath(["value"]);
				this.__dbChanges.changes.push(value != null ? { kind : "set", path : fieldPath, value : MyEnum_$_$Helper.instance.toRawValue(value)} : { kind : "delete", path : fieldPath});
			}
		}
		return value;
	}
	,__setup: function(transaction,dbChanges) {
		this.__transaction = transaction;
		this.__dbChanges = dbChanges;
	}
	,__toRawValue: function() {
		var raw = { };
		if(this.value != null) {
			raw.value = MyEnum_$_$Helper.instance.toRawValue(this.value);
		}
		return raw;
	}
});
var GameData = function() {
};
GameData.__name__ = true;
GameData.fromRawValue = function(raw) {
	return GameData.__fromRawValue(raw);
};
GameData.__fromRawValue = function(raw) {
	var instance = Object.create(GameData.prototype);
	instance.set_data(Data.__fromRawValue(raw.data));
	return instance;
};
GameData.__super__ = classy_core_Value;
GameData.prototype = $extend(classy_core_Value.prototype,{
	set_data: function(value) {
		var _gthis = this;
		var oldValue = this.data;
		if(oldValue != value) {
			if(oldValue != null) {
				oldValue.__unlink();
			}
			if(value != null) {
				value.__link(this,"data");
			}
			this.data = value;
			if(this.__transaction != null) {
				this.__transaction.rollbacks.push(function() {
					return _gthis.data = oldValue;
				});
			}
			if(this.__dbChanges != null) {
				var fieldPath = this.__makeFieldPath(["data"]);
				this.__dbChanges.changes.push(value != null ? { kind : "set", path : fieldPath, value : value.__toRawValue()} : { kind : "delete", path : fieldPath});
			}
		}
		return value;
	}
	,__setup: function(transaction,dbChanges) {
		this.__transaction = transaction;
		this.__dbChanges = dbChanges;
		if(this.data != null) {
			this.data.__setup(transaction,dbChanges);
		}
	}
});
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var data = GameData.__fromRawValue({ data : { value : "A"}});
	var dbChanges = new classy_core_DbChanges();
	data.__setup(new classy_core_Transaction(),dbChanges);
	var some = new Some();
	data.set_data(new Data());
	data.data.set_value(MyEnum.D(MyEnum2.A(some)));
	some.set_some("LOL");
	var _g = 0;
	var _g1 = dbChanges.commit();
	while(_g < _g1.length) console.log("Main.hx:71:",JSON.stringify(_g1[_g++]));
};
Math.__name__ = true;
var classy_core_Helper = function() { };
classy_core_Helper.__name__ = true;
var MyEnum2_$_$Helper = function() {
};
MyEnum2_$_$Helper.__name__ = true;
MyEnum2_$_$Helper.__interfaces__ = [classy_core_Helper];
MyEnum2_$_$Helper.prototype = {
	link: function(value,parent,name) {
		var v = value[2];
		if(v != null) {
			v.__link(parent,name + ".v");
		}
	}
	,unlink: function(value) {
		var v = value[2];
		if(v != null) {
			v.__unlink();
		}
	}
	,toRawValue: function(value) {
		var v = value[2];
		var raw = { "$tag" : "A"};
		if(v != null) {
			raw.v = v.__toRawValue();
		}
		return raw;
	}
};
var MyEnum2_$_$RawValueConverter = function() {
};
MyEnum2_$_$RawValueConverter.__name__ = true;
MyEnum2_$_$RawValueConverter.__interfaces__ = [classy_core_RawValueConverter];
MyEnum2_$_$RawValueConverter.prototype = {
	fromRawValue: function(raw) {
		var _g = Reflect.field(raw,"$tag");
		if(_g == "A") {
			return MyEnum2.A(Some.__fromRawValue(raw.v));
		} else {
			throw new js__$Boot_HaxeError("Unknown enum tag: " + _g);
		}
	}
};
var MyEnum_$_$Helper = function() {
};
MyEnum_$_$Helper.__name__ = true;
MyEnum_$_$Helper.__interfaces__ = [classy_core_Helper];
MyEnum_$_$Helper.prototype = {
	link: function(value,parent,name) {
		switch(value[1]) {
		case 0:
			break;
		case 1:
			break;
		case 2:
			var v = value[2];
			if(v != null) {
				v.__link(parent,name + ".v");
			}
			break;
		case 3:
			var e = value[2];
			if(e != null) {
				MyEnum2_$_$Helper.instance.link(e,parent,name + ".e");
			}
			break;
		}
	}
	,unlink: function(value) {
		switch(value[1]) {
		case 0:
			break;
		case 1:
			break;
		case 2:
			var v = value[2];
			if(v != null) {
				v.__unlink();
			}
			break;
		case 3:
			var e = value[2];
			if(e != null) {
				MyEnum2_$_$Helper.instance.unlink(e);
			}
			break;
		}
	}
	,toRawValue: function(value) {
		switch(value[1]) {
		case 0:
			return "A";
		case 1:
			var raw = { "$tag" : "B"};
			raw.v = value[2];
			return raw;
		case 2:
			var v = value[2];
			var raw1 = { "$tag" : "C"};
			if(v != null) {
				raw1.v = v.__toRawValue();
			}
			return raw1;
		case 3:
			var e = value[2];
			var raw2 = { "$tag" : "D"};
			if(e != null) {
				raw2.e = MyEnum2_$_$Helper.instance.toRawValue(e);
			}
			return raw2;
		}
	}
};
var MyEnum_$_$RawValueConverter = function() {
};
MyEnum_$_$RawValueConverter.__name__ = true;
MyEnum_$_$RawValueConverter.__interfaces__ = [classy_core_RawValueConverter];
MyEnum_$_$RawValueConverter.prototype = {
	fromRawValue: function(raw) {
		if(raw == "A") {
			return MyEnum.A;
		} else {
			var _g = Reflect.field(raw,"$tag");
			switch(_g) {
			case "B":
				return MyEnum.B(raw.v);
			case "C":
				return MyEnum.C(Player.__fromRawValue(raw.v));
			case "D":
				return MyEnum.D(MyEnum2_$_$RawValueConverter.instance.fromRawValue(raw.e));
			default:
				throw new js__$Boot_HaxeError("Unknown enum tag: " + _g);
			}
		}
	}
};
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		return null;
	}
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = true;
var classy_core_DbChanges = function() {
	this.changes = [];
};
classy_core_DbChanges.__name__ = true;
classy_core_DbChanges.prototype = {
	commit: function() {
		var committedChanges = this.changes;
		this.changes = [];
		return committedChanges;
	}
};
var classy_core_Transaction = function() {
	this.rollbacks = [];
};
classy_core_Transaction.__name__ = true;
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if((o instanceof Array)) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			var e1 = (e instanceof js__$Boot_HaxeError) ? e.val : e;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = true;
Array.__name__ = true;
MyEnum2_$_$Helper.instance = new MyEnum2_$_$Helper();
MyEnum2_$_$RawValueConverter.instance = new MyEnum2_$_$RawValueConverter();
MyEnum_$_$Helper.instance = new MyEnum_$_$Helper();
MyEnum_$_$RawValueConverter.instance = new MyEnum_$_$RawValueConverter();
Main.main();
})();
